const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const store = new Map();let handler, writesFail=false, requests=[],navigations=[];
global.wx={getStorageSync:k=>store.get(k),setStorageSync:(k,v)=>{if(writesFail)throw Error('disk full');store.set(k,structuredClone(v));},removeStorageSync:k=>store.delete(k),request:o=>{requests.push(o);queueMicrotask(()=>handler(o));},navigateTo:o=>navigations.push(o.url)};
global.getApp=()=>({globalData:{apiBase:'https://huangquechuanmei.com'}});global.getCurrentPages=()=>[];
const api=require('../miniprogram/paper/services/api');const c=require('../miniprogram/paper/services/creation');
const good=(o,data)=>o.success({statusCode:200,data});
function base(o){if(o.url.endsWith('/pricing'))return good(o,{items:[{key:'image.openai.std',points:20}]});if(o.url.endsWith('/me'))return good(o,{user:{username:'alice',points:100}});return false;}
const draft={kind:'image',prompt:'晨光中的茶杯'};
(async()=>{
 api.setSession({token:'fake-test-token',user:{username:'alice'}});
 assert.throws(()=>c.payload({kind:'image',prompt:' '}));
 assert.throws(()=>c.payload({kind:'audio',prompt:'你好'}),/音色/);
 assert.equal(c.payload({kind:'video',prompt:'茶园晨雾'}).resolution,'768p');
 assert.match(c.format('video').detail,/768P/);
 assert.equal(api.mediaURL('javascript:alert(1)'), '');assert.equal(api.mediaURL('//other/a'), '');assert.equal(api.mediaURL('/out/a.png'),api.BASE+'/out/a.png');
 handler=o=>o.url.endsWith('/image')?o.fail():base(o);
 await assert.rejects(c.submit(draft,20),/网络/);
 const key=api.read().attempt.key;assert.equal(api.read().attempt.status,'unknown');
 await assert.rejects(c.submit(draft,20),/尚未确认/);
 handler=o=>o.url.endsWith('/image')?good(o,{job_id:12}):base(o);
 await c.submit(null,null,true);assert.equal(api.read().attempt.key,key);assert.equal(api.read().selected.id,12);
 assert.equal(requests.filter(o=>o.url.endsWith('/image')).length,2);
 assert.equal(requests.filter(o=>o.url.endsWith('/image'))[1].header['Idempotency-Key'],key);
 const before=requests.length;writesFail=true;await assert.rejects(c.submit(draft,20),/disk full/);writesFail=false;
 assert.equal(requests.slice(before).some(o=>o.url.endsWith('/image')),false);
 const count=requests.length;await assert.rejects(c.submit(draft,99),/价格/);assert.equal(requests.slice(count).some(o=>o.url.endsWith('/image')),false);
 // Malformed success is ambiguous, and an error carrying a job ID remains discoverable.
 handler=o=>o.url.endsWith('/image')?good(o,'proxy error'):base(o);
 await assert.rejects(c.submit(draft,20));assert.equal(api.read().attempt.status,'unknown');
 handler=o=>o.url.endsWith('/image')?o.success({statusCode:503,data:{job_id:13,detail:'provider failure'}}):base(o);
 await c.submit(null,null,true);assert.equal(api.read().selected.id,13);assert(api.read().jobIds.includes(13));
 handler=o=>o.url.endsWith('/me')?good(o,{user:{username:'alice',points:1}}):base(o);
 const low=requests.length;await assert.rejects(c.submit(draft,20),/积分不足/);assert(!requests.slice(low).some(o=>o.method==='POST'));
 let releaseQuote;handler=o=>{if(o.url.endsWith('/pricing'))releaseQuote=o;else if(o.url.endsWith('/image'))good(o,{job_id:14});else base(o);};
 const pending=c.submit(draft,20);await assert.rejects(c.submit(draft,20),/正在提交/);
 good(releaseQuote,{items:[{key:'image.openai.std',points:20}]});await pending;
 api.setSession({token:'bob-token',user:{username:'bob'}});assert.equal(api.read().attempt,undefined);
 assert.equal(store.get('hq_token'),'bob-token');assert.equal(store.get('hq-paper-session-v1'),undefined);
 assert.deepEqual(api.mediaHeaders('https://cdn.example.com/a.mp4'),{});assert.equal(api.mediaHeaders(api.BASE+'/api/gen/file/1').Authorization,'Bearer bob-token');assert.equal(api.mediaHeaders(api.BASE+'/workbench/ip12/api/v4/media/a.jpg').Authorization,'Bearer bob-token');
 handler=o=>good(o,{sessions:[]});assert.deepEqual(await api.request('/workbench/ip12/api/v4/sessions','GET',null,{timeout:180000}),{sessions:[]});assert.match(requests.at(-1).url,/\/workbench\/ip12\/api\/v4\/sessions$/);assert.equal(requests.at(-1).timeout,180000);
 handler=o=>o.success({statusCode:409,data:{error:'页面状态已经变化'}});await assert.rejects(api.request('/workbench/ip12/api/v4/sessions'),/页面状态已经变化/);
 let release;handler=o=>{release=o;};const p=api.request('/api/auth/me');await new Promise(r=>setImmediate(r));api.setSession({token:'new-token',user:{username:'charlie'}});release.success({statusCode:401,data:{detail:'expired'}});await assert.rejects(p);assert.equal(api.session().token,'new-token');
 handler=o=>o.success({statusCode:401,data:{detail:'expired'}});await assert.rejects(api.request('/api/auth/me'));assert.equal(api.session(),null);
 const j=c.jobView({id:1,kind:'image',status:'error',refunded:false,cost:20});assert.equal(j.refunded,false);assert.equal(j.failed,true);
 const config=JSON.parse(fs.readFileSync(path.join(__dirname,'../miniprogram/app.json')));const wxml=fs.readFileSync(path.join(__dirname,'../miniprogram/paper/components/screen/index.wxml'),'utf8');
 assert.match(wxml,/class="hq-view agent-status"/);assert.match(wxml,/wx:for="{{agentMessages}}"/);assert.match(wxml,/class="hq-view agent-composer"/);assert.match(wxml,/'\u53d1\u9001'/);assert.doesNotMatch(wxml,/\u65b9\u6848\u6574\u7406\u6a21\u5f0f|\u8ba9 Agent \u6574\u7406\u65b9\u6848|\u5f53\u524d\u4e0a\u4e0b\u6587/);
 const screenJs=fs.readFileSync(path.join(__dirname,'../miniprogram/paper/components/screen/index.js'),'utf8');
 assert.match(screenJs,/IP12_API = '\/workbench\/ip12\/api\/v4'/);assert.match(screenJs,/IP12_API\+'\/sessions'/);assert.match(screenJs,/IP12_API\+'\/chat'/);assert.match(screenJs,/\/api\/gen\/video\/assets/);assert.doesNotMatch(screenJs,/\/api\/creator-agent/);
 assert.match(wxml,/class="hq-view easy-prompts"/);assert.match(wxml,/class="hq-view works-list"/);assert.doesNotMatch(wxml,/data-legacy="home"/);
 for(const route of config.subPackages.find(p=>p.root==='paper').pages){const cfg=JSON.parse(fs.readFileSync(path.join(__dirname,'../miniprogram/paper',route+'.json')));assert.equal(cfg.usingComponents['paper-screen'],'/paper/components/screen/index');for(const ext of ['js','json','wxml'])assert(fs.existsSync(path.join(__dirname,'../miniprogram/paper',route+'.'+ext)));assert(wxml.includes("pageId==='"+route.split('/')[1]+"'"),route);}
 let component;global.Component=x=>component=x;require('../miniprogram/paper/components/screen/index');
 for(const match of wxml.matchAll(/data-route="([a-z-]+)"/g))assert(config.subPackages[0].pages.includes('pages/'+match[1]+'/index'),match[1]);
 for(const match of wxml.matchAll(/bind(?:tap|input|change|error)="([A-Za-z]\w*)"/g))assert.equal(typeof component.methods[match[1]],'function',match[1]);
 const shortcut={data:{},setData(p){Object.assign(this.data,p);}};component.methods.homeShortcut.call(shortcut,{currentTarget:{dataset:{prompt:'我想做视频'}}});assert.equal(shortcut.data.promptInput,'我想做视频');
 api.setSession({token:'fake-test-token',user:{username:'alice'}});
 const homeStart={data:{promptInput:'你好'},setData(){},requireLogin:()=>true,navigate(route){this.route=route;}};component.methods.startChat.call(homeStart);assert.equal(homeStart.route,'chat');assert.equal(api.read().ip12Outgoing.message,'你好');
 const paperRequest=api.request;api.request=async(path,method,data)=>{
   if(path==='/workbench/ip12/api/v4/sessions')return {sessions:[{sid:'sid-1',preview:'网页上的同一段对话'}]};
   if(path==='/workbench/ip12/api/v4/chat'){assert.equal(method,'POST');assert.deepEqual(data,{session_id:'sid-1',message:'你好'});return {async:true,seq:9};}
   if(path==='/workbench/ip12/api/v4/poll/sid-1')return {state:'done',seq:9,reply:'你好，请慢慢说。'};
   if(path==='/workbench/ip12/api/v4/restore/sid-1')return {ok:true,history:[{role:'user',content:'你好'},{role:'assistant',content:'你好，请慢慢说。'}],delegations:{},report:{}};
   throw Error(path);
 };
 const loader={alive:true,properties:{pageId:'home'},data:{agentMessages:[]},setData(p){Object.assign(this.data,p);},restoreAgent:component.methods.restoreAgent,scrollAgent(){}};await component.methods.loadAgent.call(loader);assert.equal(loader.data.agentSessionId,'sid-1');assert.equal(loader.data.agentMessages[1].content,'你好，请慢慢说。');
 const chat={alive:true,data:{promptInput:'你好',agentSessionId:'sid-1',agentMessages:[],agentPending:null,agentDelegations:[]},setData(p){Object.assign(this.data,p);},run:component.methods.run,executeAgent:component.methods.executeAgent,pollAgent:component.methods.pollAgent,restoreAgent:component.methods.restoreAgent,ensureAgentSession:component.methods.ensureAgentSession,sendAgentMessage:component.methods.sendAgentMessage,sendAgent:component.methods.sendAgent,scrollAgent(){},requireLogin:()=>true,fail(e){throw e;}};
 await component.methods.sendPrompt.call(chat);assert.equal(chat.data.promptInput,'');assert.deepEqual(chat.data.agentMessages.map(x=>x.content),['你好','你好，请慢慢说。']);assert.equal(api.read().ip12Pending,null);assert.equal(api.read().ip12Waiting,null);api.request=paperRequest;
 const paperMediaSource=api.mediaSource;let sharedFile;
 api.mediaSource=async url=>{assert.match(url,/\/workbench\/ip12\/api\/v4\/export\/sid-1\.jsonl$/);return '/tmp/chat.jsonl';};
 wx.shareFileMessage=options=>{sharedFile=options;options.success();};
 await component.methods.exportAgentConversation.call({data:{agentSessionId:'sid-1'},run:fn=>fn(),toast(){}});assert.equal(sharedFile.filePath,'/tmp/chat.jsonl');assert.match(sharedFile.fileName,/^黄雀对话-\d{8}\.jsonl$/);api.mediaSource=paperMediaSource;
 const ctx={alive:true,data:{works:[{key:'job-12',id:12,done:true,kind:'image',url:'https://example.com/a.png',title:'茶杯'}],card:{works:[]}},requireLogin:()=>true,setData(p){Object.assign(this.data,p);},toast(){},run:fn=>(ctx.pending=fn())};
 wx.downloadFile=o=>o.success({statusCode:200,tempFilePath:'/test-image'});
 wx.getFileSystemManager=()=>({getFileInfo:o=>o.success({size:200}),readFile:o=>o.success({data:'iVBORtest'}),unlink(){}});
 handler=o=>{if(o.url.includes('/card/me?'))return good(o,{card:{works:[{type:'image',slot:1,key:'owned-key'}]}});if(o.url.endsWith('/card/media')){assert.equal(o.data.field,'work_image_2');assert(o.data.data.startsWith('data:image/png;base64,'));return good(o,{card:{works:[{key:'new-owned-key'}]}});}throw Error(o.url);};
 component.methods.toggleFeatured.call(ctx,{currentTarget:{dataset:{key:'job-12'}}});await ctx.pending;assert.equal(ctx.data.card.works[0].key,'new-owned-key');
 wx.getFileSystemManager=()=>({getFileInfo:o=>o.success({size:5*1024*1024}),unlink(){}});
 const uploads=requests.filter(o=>o.url.endsWith('/card/media')).length;
 component.methods.toggleFeatured.call(ctx,{currentTarget:{dataset:{key:'job-12'}}});await assert.rejects(ctx.pending,/4 MB/);
 assert.equal(requests.filter(o=>o.url.endsWith('/card/media')).length,uploads);
 handler=o=>good(o,{items:[{voice_key:'voice-a',display_name:'声线 A',ready:true},{voice_key:'voice-b',ready:false}]});
 await component.methods.loadVoices.call(ctx);assert.deepEqual(ctx.data.voices,[{key:'voice-a',name:'声线 A'}]);
 api.setSession({token:'logout-token',user:{username:'alice'}});
 api.request=async()=>{throw Error('offline')};
 const logout={data:{},alive:true,setData(p){Object.assign(this.data,p);},navigate(route){this.route=route;},run(fn){this.pending=fn();}};
 component.methods.logout.call(logout);await logout.pending;assert.equal(api.session(),null);assert.equal(logout.route,'login');
 api.setSession({token:'fake-test-token',user:{username:'alice'}});
 let resolved=0;api.mediaSource=async url=>{resolved+=1;return url;};
 api.request=async path=>path.includes('kind=image')?{items:Array.from({length:30},(_,i)=>({id:i+1,kind:'image',status:'done',url:'/api/gen/file/'+i,prompt:'图片'+i}))}:path.includes('/video/assets')?{items:[{id:7,job_id:99,status:'done',video_url:'/api/gen/file/video/v.mp4',image_file:'video/c.jpg',ratio:'16:9',text:'网页视频'}]}:{items:[]};
 const home={alive:true,properties:{pageId:'home'},data:{search:'',filter:'all'},setData(p){Object.assign(this.data,p);},applyFilter:component.methods.applyFilter};
 await component.methods.loadWorks.call(home);assert.equal(resolved,3);assert.equal(home.data.works[0].title,'网页视频');assert.equal(home.data.works[0].videoHeight,390);assert.match(home.data.works[0].displayCover,/video\/c.jpg/);
 let active=0,maxActive=0;api.mediaSource=async url=>{active+=1;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setImmediate(resolve));active-=1;return url;};
 const works={alive:true,properties:{pageId:'works'},data:{search:'',filter:'all'},setData(p){Object.assign(this.data,p);},applyFilter:component.methods.applyFilter};
 await component.methods.loadWorks.call(works);assert.equal(maxActive,4);
 const statusFilter={properties:{pageId:'works'},data:{search:'',filter:'failed',works:[{id:1,title:'完成',done:true,failed:false},{id:2,title:'失败',done:false,failed:true},{id:3,title:'处理中',done:false,failed:false}]},setData(p){Object.assign(this.data,p);}};component.methods.applyFilter.call(statusFilter);assert.deepEqual(statusFilter.data.visibleWorks.map(x=>x.id),[2]);
 assert.equal(JSON.parse(fs.readFileSync(path.join(__dirname,'../project.config.json'))).appid,'wx23904aa2aa91f4d6');
 const shared=require('../miniprogram/utils/api');
 assert.equal(shared.loginRedirect('paper/pages/chat/index'),'paper');assert.equal(shared.loginRedirect('https://evil.example/paper'),'');
 let download;wx.downloadFile=o=>{download=o;o.success({statusCode:200,tempFilePath:'/tmp/local'});};
 await shared.downloadProtected('https://cdn.example.com/test.png');assert.equal(download.header.Authorization,undefined);
 await shared.downloadProtected(api.BASE+'/api/gen/file/12');assert.equal(download.header.Authorization,'Bearer fake-test-token');
 await shared.downloadProtected(api.BASE+'/workbench/ip12/api/report.pdf');assert.equal(download.header.Authorization,'Bearer fake-test-token');
 shared.setToken('another-token');await shared.downloadProtected(api.BASE+'/api/gen/file/12');assert.equal(download.header.Authorization,'Bearer another-token');
 assert.equal(api.session().user.username,'');assert.throws(()=>api.save({draft}),/核对账号/);
 console.log('PASS: 26 routes, event bindings, payload validation, media URLs, quote changes, durable submission, recovery key, account isolation stale 401, malformed response, low balance, double submit, card upload limits and voice contract');
})().catch(e=>{console.error(e);process.exitCode=1;});
