const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const store = new Map();let handler, writesFail=false, requests=[],navigations=[];
global.wx={getStorageSync:k=>store.get(k),setStorageSync:(k,v)=>{if(writesFail)throw Error('disk full');store.set(k,structuredClone(v));},removeStorageSync:k=>store.delete(k),request:o=>{requests.push(o);queueMicrotask(()=>handler(o));},navigateTo:o=>navigations.push(o.url)};
global.getApp=()=>({globalData:{apiBase:'https://huangquechuanmei.com'}});global.getCurrentPages=()=>[];
const api=require('../miniprogram/paper/services/api');const c=require('../miniprogram/paper/services/creation');
const good=(o,data)=>o.success({statusCode:200,data});
function base(o){if(o.url.endsWith('/pricing'))return good(o,{items:[{key:'image.openai.std',points:20}]});if(o.url.endsWith('/me'))return good(o,{user:{username:'alice',points:100}});return false;}
const draft={kind:'image',prompt:'晨光中的茶杯'};
(async()=>{
 api.setSession({token:'fake-test-token',user:{username:'alice'}});
 assert.throws(()=>c.payload({kind:'image',prompt:' '}));
 assert.throws(()=>c.payload({kind:'audio',prompt:'你好'}),/音色/);
 assert.equal(c.payload({kind:'video',prompt:'茶园晨雾'}).resolution,'768p');
 assert.match(c.format('video').detail,/768P/);
 assert.equal(api.mediaURL('javascript:alert(1)'), '');assert.equal(api.mediaURL('//other/a'), '');assert.equal(api.mediaURL('/out/a.png'),api.BASE+'/out/a.png');
 handler=o=>o.url.endsWith('/image')?o.fail():base(o);
 await assert.rejects(c.submit(draft,20),/网络/);
 const key=api.read().attempt.key;assert.equal(api.read().attempt.status,'unknown');
 await assert.rejects(c.submit(draft,20),/尚未确认/);
 handler=o=>o.url.endsWith('/image')?good(o,{job_id:12}):base(o);
 await c.submit(null,null,true);assert.equal(api.read().attempt.key,key);assert.equal(api.read().selected.id,12);
 assert.equal(requests.filter(o=>o.url.endsWith('/image')).length,2);
 assert.equal(requests.filter(o=>o.url.endsWith('/image'))[1].header['Idempotency-Key'],key);
 const before=requests.length;writesFail=true;await assert.rejects(c.submit(draft,20),/disk full/);writesFail=false;
 assert.equal(requests.slice(before).some(o=>o.url.endsWith('/image')),false);
 const count=requests.length;await assert.rejects(c.submit(draft,99),/价格/);assert.equal(requests.slice(count).some(o=>o.url.endsWith('/image')),false);
 // Malformed success is ambiguous, and an error carrying a job ID remains discoverable.
 handler=o=>o.url.endsWith('/image')?good(o,'proxy error'):base(o);
 await assert.rejects(c.submit(draft,20));assert.equal(api.read().attempt.status,'unknown');
 handler=o=>o.url.endsWith('/image')?o.success({statusCode:503,data:{job_id:13,detail:'provider failure'}}):base(o);
 await c.submit(null,null,true);assert.equal(api.read().selected.id,13);assert(api.read().jobIds.includes(13));
 handler=o=>o.url.endsWith('/me')?good(o,{user:{username:'alice',points:1}}):base(o);
 const low=requests.length;await assert.rejects(c.submit(draft,20),/积分不足/);assert(!requests.slice(low).some(o=>o.method==='POST'));
 let releaseQuote;handler=o=>{if(o.url.endsWith('/pricing'))releaseQuote=o;else if(o.url.endsWith('/image'))good(o,{job_id:14});else base(o);};
 const pending=c.submit(draft,20);await assert.rejects(c.submit(draft,20),/正在提交/);
 good(releaseQuote,{items:[{key:'image.openai.std',points:20}]});await pending;
 api.setSession({token:'bob-token',user:{username:'bob'}});assert.equal(api.read().attempt,undefined);
 assert.equal(store.get('hq_token'),'bob-token');assert.equal(store.get('hq-paper-session-v1'),undefined);
 assert.deepEqual(api.mediaHeaders('https://cdn.example.com/a.mp4'),{});assert.equal(api.mediaHeaders(api.BASE+'/api/gen/file/1').Authorization,'Bearer bob-token');
 let release;handler=o=>{release=o;};const p=api.request('/api/auth/me');await new Promise(r=>setImmediate(r));api.setSession({token:'new-token',user:{username:'charlie'}});release.success({statusCode:401,data:{detail:'expired'}});await assert.rejects(p);assert.equal(api.session().token,'new-token');
 handler=o=>o.success({statusCode:401,data:{detail:'expired'}});await assert.rejects(api.request('/api/auth/me'));assert.equal(api.session(),null);
 const j=c.jobView({id:1,kind:'image',status:'error',refunded:false,cost:20});assert.equal(j.refunded,false);assert.equal(j.failed,true);
 const config=JSON.parse(fs.readFileSync(path.join(__dirname,'../miniprogram/app.json')));const wxml=fs.readFileSync(path.join(__dirname,'../miniprogram/paper/components/screen/index.wxml'),'utf8');
 assert.match(wxml,/class="hq-view agent-status"/);assert.match(wxml,/class="hq-view user-message"/);assert.match(wxml,/class="hq-view agent-composer"/);assert.match(wxml,/>\u8ba9 Agent \u6574\u7406\u65b9\u6848 \u2192</);assert.doesNotMatch(wxml,/Agent \u5728\u7ebf/);
 assert.match(wxml,/class="hq-view home-shortcuts"/);assert.match(wxml,/class="hq-view works-list"/);assert.doesNotMatch(wxml,/data-legacy="home"/);
 for(const route of config.subPackages.find(p=>p.root==='paper').pages){const cfg=JSON.parse(fs.readFileSync(path.join(__dirname,'../miniprogram/paper',route+'.json')));assert.equal(cfg.usingComponents['paper-screen'],'/paper/components/screen/index');for(const ext of ['js','json','wxml'])assert(fs.existsSync(path.join(__dirname,'../miniprogram/paper',route+'.'+ext)));assert(wxml.includes("pageId==='"+route.split('/')[1]+"'"),route);}
 let component;global.Component=x=>component=x;require('../miniprogram/paper/components/screen/index');
 for(const match of wxml.matchAll(/data-route="([a-z-]+)"/g))assert(config.subPackages[0].pages.includes('pages/'+match[1]+'/index'),match[1]);
 for(const match of wxml.matchAll(/bind(?:tap|input|change|error)="([A-Za-z]\w*)"/g))assert.equal(typeof component.methods[match[1]],'function',match[1]);
 const shortcut={data:{},setData(p){Object.assign(this.data,p);},openLegacy:component.methods.openLegacy};component.methods.homeShortcut.call(shortcut,{currentTarget:{dataset:{action:'video'}}});assert.equal(shortcut.data.kind,'video');component.methods.homeShortcut.call(shortcut,{currentTarget:{dataset:{action:'inspiration'}}});assert.deepEqual(navigations,['/pages/inspiration/inspiration']);
 api.setSession({token:'fake-test-token',user:{username:'alice'}});
 const ctx={alive:true,data:{works:[{id:12,done:true,kind:'image',url:'https://example.com/a.png',title:'茶杯'}],card:{works:[]}},requireLogin:()=>true,setData(p){Object.assign(this.data,p);},toast(){},run:fn=>(ctx.pending=fn())};
 wx.downloadFile=o=>o.success({statusCode:200,tempFilePath:'/test-image'});
 wx.getFileSystemManager=()=>({getFileInfo:o=>o.success({size:200}),readFile:o=>o.success({data:'iVBORtest'}),unlink(){}});
 handler=o=>{if(o.url.includes('/card/me?'))return good(o,{card:{works:[{type:'image',slot:1,key:'owned-key'}]}});if(o.url.endsWith('/card/media')){assert.equal(o.data.field,'work_image_2');assert(o.data.data.startsWith('data:image/png;base64,'));return good(o,{card:{works:[{key:'new-owned-key'}]}});}throw Error(o.url);};
 component.methods.toggleFeatured.call(ctx,{currentTarget:{dataset:{id:12}}});await ctx.pending;assert.equal(ctx.data.card.works[0].key,'new-owned-key');
 wx.getFileSystemManager=()=>({getFileInfo:o=>o.success({size:5*1024*1024}),unlink(){}});
 const uploads=requests.filter(o=>o.url.endsWith('/card/media')).length;
 component.methods.toggleFeatured.call(ctx,{currentTarget:{dataset:{id:12}}});await assert.rejects(ctx.pending,/4 MB/);
 assert.equal(requests.filter(o=>o.url.endsWith('/card/media')).length,uploads);
 handler=o=>good(o,{items:[{voice_key:'voice-a',display_name:'声线 A',ready:true},{voice_key:'voice-b',ready:false}]});
 await component.methods.loadVoices.call(ctx);assert.deepEqual(ctx.data.voices,[{key:'voice-a',name:'声线 A'}]);
 api.setSession({token:'logout-token',user:{username:'alice'}});
 api.request=async()=>{throw Error('offline')};
 const logout={data:{},alive:true,setData(p){Object.assign(this.data,p);},navigate(route){this.route=route;},run(fn){this.pending=fn();}};
 component.methods.logout.call(logout);await logout.pending;assert.equal(api.session(),null);assert.equal(logout.route,'login');
 api.setSession({token:'fake-test-token',user:{username:'alice'}});
 let resolved=0;api.mediaSource=async url=>{resolved+=1;return url;};
 api.request=async path=>path.includes('kind=image')?{items:Array.from({length:30},(_,i)=>({id:i+1,kind:'image',status:'done',url:'/api/gen/file/'+i,prompt:'图片'+i}))}:{items:[]};
 const home={alive:true,properties:{pageId:'home'},data:{search:'',filter:'all'},setData(p){Object.assign(this.data,p);},applyFilter:component.methods.applyFilter};
 await component.methods.loadWorks.call(home);assert.equal(resolved,3);
 let active=0,maxActive=0;api.mediaSource=async url=>{active+=1;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setImmediate(resolve));active-=1;return url;};
 const works={alive:true,properties:{pageId:'works'},data:{search:'',filter:'all'},setData(p){Object.assign(this.data,p);},applyFilter:component.methods.applyFilter};
 await component.methods.loadWorks.call(works);assert.equal(maxActive,4);
 const statusFilter={properties:{pageId:'works'},data:{search:'',filter:'failed',works:[{id:1,title:'完成',done:true,failed:false},{id:2,title:'失败',done:false,failed:true},{id:3,title:'处理中',done:false,failed:false}]},setData(p){Object.assign(this.data,p);}};component.methods.applyFilter.call(statusFilter);assert.deepEqual(statusFilter.data.visibleWorks.map(x=>x.id),[2]);
 assert.equal(JSON.parse(fs.readFileSync(path.join(__dirname,'../project.config.json'))).appid,'wx23904aa2aa91f4d6');
 const shared=require('../miniprogram/utils/api');
 assert.equal(shared.loginRedirect('paper/pages/chat/index'),'paper');assert.equal(shared.loginRedirect('https://evil.example/paper'),'');
 let download;wx.downloadFile=o=>{download=o;o.success({statusCode:200,tempFilePath:'/tmp/local'});};
 await shared.downloadProtected('https://cdn.example.com/test.png');assert.equal(download.header.Authorization,undefined);
 await shared.downloadProtected(api.BASE+'/api/gen/file/12');assert.equal(download.header.Authorization,'Bearer fake-test-token');
 await shared.downloadProtected(api.BASE+'/workbench/ip12/api/report.pdf');assert.equal(download.header.Authorization,'Bearer fake-test-token');
 shared.setToken('another-token');await shared.downloadProtected(api.BASE+'/api/gen/file/12');assert.equal(download.header.Authorization,'Bearer another-token');
 assert.equal(api.session().user.username,'');assert.throws(()=>api.save({draft}),/核对账号/);
 console.log('PASS: 26 routes, event bindings, payload validation, media URLs, quote changes, durable submission, recovery key, account isolation stale 401, malformed response, low balance, double submit, card upload limits and voice contract');
})().catch(e=>{console.error(e);process.exitCode=1;});
