const test=require('node:test'),assert=require('node:assert/strict');
const store=new Map();global.wx={getStorageSync:k=>store.get(k),setStorageSync:(k,v)=>store.set(k,structuredClone(v)),removeStorageSync:k=>store.delete(k)};
global.getApp=()=>({globalData:{apiBase:'https://huangquechuanmei.com'}});global.getCurrentPages=()=>[];
let definition;global.Component=c=>definition=c;require('../miniprogram/paper/components/screen/index');
const api=require('../miniprogram/paper/services/api');
function setup(){store.clear();api.setSession({token:'isolated-test',user:{username:'test'}});api.save({ip12Waiting:{sid:'s',seq:2}});return Object.assign({},definition.methods,{alive:true,visible:true,properties:{pageId:'home'},data:{agentSessionId:'s',promptInput:'next draft'},setData(p){Object.assign(this.data,p);},requireLogin:()=>true,navigate(route){this.route=route;}});}
test('working homepage opens original chat without submitting and retains draft',async()=>{const c=setup();api.request=async()=>({state:'working',seq:2});await c.refreshHomeAgent();assert.equal(c.data.agentHomeAction,'查看进度');c.startChat();c.startChat();assert.equal(c.route,'chat');assert.equal(api.read().ip12Outgoing,null);assert.deepEqual(api.read().ip12HomeDraft,{sid:'s',message:'next draft'});c.stopHomeAgent();});
test('completed waiting clears only matching record and shows reply entry',async()=>{const c=setup();api.request=async()=>({state:'done',seq:2});await c.refreshHomeAgent();assert.equal(api.read().ip12Waiting,null);assert.equal(c.data.agentHomeAction,'查看回复');assert.equal(c.data.agentThinking,false);c.stopHomeAgent();});
test('offline preserves waiting and usable entry with slower retry',async()=>{const c=setup();api.request=async()=>{throw Error('offline');};await c.refreshHomeAgent();assert.equal(c.data.agentHomeAction,'查看对话');assert.equal(api.read().ip12Waiting.seq,2);assert(c.homeAgentTimer);c.startChat();assert.equal(api.read().ip12HomeDraft.message,'next draft');c.stopHomeAgent();});
test('late completion cannot clear a newer sequence',async()=>{const c=setup();let finish;api.request=()=>new Promise(r=>finish=r);const p=c.refreshHomeAgent();api.save({ip12Waiting:{sid:'s',seq:3}});finish({state:'done',seq:2});await p;assert.equal(api.read().ip12Waiting.seq,3);c.stopHomeAgent();});
test('switch new conversation cancels old homepage query and unlocks entry',async()=>{const c=setup();let finish;api.request=()=>new Promise(r=>finish=r);const p=c.refreshHomeAgent();c.useNewHomeAgentSession();finish({state:'done',seq:2});await p;assert.equal(c.data.agentSessionId,'');assert.equal(c.data.agentHomeAction,'开始');assert.equal(api.read().ip12Waiting.seq,2);assert.equal(c.homeAgentTimer,null);});
test('idle history without reliable sequence does not discard wait',async()=>{const c=setup();api.request=async p=>p.includes('/poll/')?{state:'idle'}:{history:[{role:'assistant',content:'older reply'}]};await c.refreshHomeAgent();assert.equal(api.read().ip12Waiting.seq,2);assert.equal(c.data.agentHomeAction,'查看对话');c.stopHomeAgent();});
test('hidden homepage discards late query and stops polling',async()=>{const c=setup();let finish;api.request=()=>new Promise(r=>finish=r);const p=c.refreshHomeAgent();c.visible=false;c.stopHomeAgent();finish({state:'working'});await p;assert.equal(c.homeAgentTimer,null);assert.equal(api.read().ip12Waiting.seq,2);});
