const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const videoJs = fs.readFileSync(path.join(root, 'miniprogram/pages/video/video.js'), 'utf8');
const videoWxml = fs.readFileSync(path.join(root, 'miniprogram/pages/video/video.wxml'), 'utf8');
const homeWxml = fs.readFileSync(path.join(root, 'miniprogram/pages/home/home.wxml'), 'utf8');
const audioJs = fs.readFileSync(path.join(root, 'miniprogram/pages/audio/audio.js'), 'utf8');
const bananaJs = fs.readFileSync(path.join(root, 'miniprogram/pages/banana/banana.js'), 'utf8');
const pricingJs = fs.readFileSync(path.join(root, 'miniprogram/utils/pricing.js'), 'utf8');
const cloneJs = fs.readFileSync(path.join(root, 'miniprogram/pages/clone/clone.js'), 'utf8');

assert.match(videoJs, /_genPricingHint\(\)/);
assert.match(videoJs, /perSec \+ ' 点\/秒 × ' \+ d\.grokDur \+ ' 秒 = ' \+ total \+ ' 点/);
assert.match(videoJs, /selectGrokModel[\s\S]*?_syncGenPricing\(\)/);
assert.match(videoJs, /selectGrokRes[\s\S]*?_syncGenPricing\(\)/);
assert.match(videoJs, /selectGrokDur[\s\S]*?_syncGenPricing\(\)/);
assert.match(videoJs, /const GROK_DURATIONS = \[5, 8, 10\]/);
assert.match(videoJs, /grokDur > 10[\s\S]*?果肉视频最长支持 10 秒/);
assert.match(videoJs, /grok-imagine-video-1\.5' && this\.data\.refPreviews\.length < 1/);
assert.match(videoJs, /engineRefMax: GEN_MAX_REF/);
assert.match(videoJs, /必选 · 最多 7 张/);
assert.match(videoJs, /使用参考图时仅支持 720p/);
assert.match(videoJs, /talking: '数字人口播每 30 秒一档实时计价/);
assert.match(videoJs, /PRICE_KEYS =/);
assert.match(videoJs, /'video\.talking\.block'/);
assert.doesNotMatch(videoJs, /const (?:CINE_RATES|AVATAR_COST|VIDEO_COST|TRYON_COST|GROK_PRICE)/);
assert.match(audioJs, /pricing\.point\(prices, 'audio\.tts'\)/);
assert.doesNotMatch(audioJs, /const COST\s*=/);
assert.match(bananaJs, /'image\.banana\.nb2\.std'/);
assert.doesNotMatch(bananaJs, /const COSTBASE\s*=/);
assert.match(pricingJs, /'\/api\/gen\/pricing'/);
assert.match(pricingJs, /const REFRESH_MS = 30000/);
assert.match(cloneJs, /pricing\.point\(prices, 'audio\.voice_slot'\)/);
assert.doesNotMatch(cloneJs, /slotCost:\s*50|slot_cost \|\| 50/);
assert.doesNotMatch(videoWxml, /mode-price/);
assert.doesNotMatch(videoWxml, />出片方式</);
assert.doesNotMatch(videoWxml, /bindtap="toggleTalkBatch"/);
assert.doesNotMatch(videoWxml, /新建 2 点/);
assert.match(videoJs, /talkBatch: false/);
assert.strictEqual((videoWxml.match(/note \|\| defaultHint/g) || []).length, 4);
assert.match(homeWxml, /videoFromPrice \? videoFromPrice \+ ' 点\/秒起'/);
assert.doesNotMatch(homeWxml, />10 点\/秒起</);
assert.doesNotMatch(homeWxml, /30 点\/30 秒/);

console.log('pricing display tests passed');
