const test=require('node:test'),assert=require('node:assert/strict');const Controller=require('../miniprogram/paper/services/task-queue-controller');const queue=require('../miniprogram/paper/services/task-queue');
function setup(request){let scope={alive:true,visible:true,sid:'s',token:'old'},tasks=queue.merge([],[{id:1,status:'running'}],'s'),updates=[];const c=new Controller({scope:()=>scope,tasks:()=>tasks,request,update:(t,r)=>{tasks=t;updates.push({tasks:t,reconnecting:r});}});return {c,scope,updates,tasks:()=>tasks};}
test('missing individual job does not block remaining completion',async()=>{const urls=[];const x=setup(async p=>{urls.push(p);if(p.includes('/status/'))return {jobs:[{id:2,status:'running'},{id:1,status:'running'}]};if(p.endsWith('/2'))throw {status:404};return {id:1,status:'done'};});await x.c.refresh();assert(urls.includes('/api/gen/job/1'));assert.equal(x.tasks().length,1);assert.equal(x.tasks()[0].status,'done');x.c.stop();});
test('individual disconnect retains discoveries and refreshes other jobs',async()=>{const x=setup(async p=>{if(p.includes('/status/'))return {jobs:[{id:2,status:'running'},{id:1,status:'running'}]};if(p.endsWith('/2'))throw Error('offline');return {id:1,status:'done'};});await x.c.refresh();assert.equal(x.tasks().find(t=>t.id==='1').status,'done');assert(x.tasks().find(t=>t.id==='2'));assert.equal(x.updates[0].reconnecting,true);x.c.stop();});
test('401 clears old tasks after request already cleared token',async()=>{let x;x=setup(async()=>{x.scope.token=null;throw {status:401};});await x.c.refresh();assert.equal(x.tasks().length,0);assert.equal(x.c.timer,null);x.c.stop();});
test('late old-account failure does not erase new account tasks',async()=>{let reject;const x=setup(()=>new Promise((_,r)=>reject=r));const pending=x.c.refresh();x.scope.token='new';reject({status:401});await pending;assert.equal(x.updates.length,0);x.c.stop();});
test('disconnect preserves task and schedules retry, recovery stops on done',async()=>{let disconnected=true;const x=setup(async p=>{if(disconnected)throw Error('offline');return p.includes('/status/')?{jobs:[{id:1,status:'running'}]}:{id:1,status:'done',kind:'copy',result:{text:'result'}};});await x.c.refresh();assert.equal(x.tasks()[0].status,'running');assert.equal(x.updates[0].reconnecting,true);assert(x.c.timer);disconnected=false;await x.c.refresh();assert.equal(x.tasks()[0].status,'done');assert.equal(x.c.timer,null);x.c.stop();});
test('specific clicked terminal task gets fresh query',async()=>{const urls=[];const x=setup(async p=>{urls.push(p);return p.includes('/status/')?{jobs:[{id:1,status:'done'}]}:{id:1,status:'done',result:{text:'new'}};});await x.c.refresh('1');assert(urls.includes('/api/gen/job/1'));assert.equal(x.tasks()[0].result.text,'new');x.c.stop();});
test('hidden view and stopped request cannot update or continue polling',async()=>{let finish;const x=setup(()=>new Promise(r=>finish=r));const p=x.c.refresh();x.scope.visible=false;x.c.stop();finish({jobs:[{id:1,status:'done'}]});await p;assert.equal(x.updates.length,0);assert.equal(x.c.timer,null);});
test('partial status preserves results, creation date and refund',()=>{let t=queue.merge([],[{id:1,status:'done',created_at:123,refunded:true,result:{text:'keep'}}],'s');t=queue.merge(t,[{id:1,state:'done'}],'s');assert.equal(t[0].result.text,'keep');assert.equal(t[0].createdAt,123);assert.equal(t[0].billing,'已退款');});
test('component clears absent or foreign detail and emits click refresh',()=>{let definition;const before=global.Component;global.Component=x=>definition=x;require('../miniprogram/paper/components/task-queue/index');global.Component=before;const c={data:{selected:{id:'1',sid:'old'}},setData(x){Object.assign(this.data,x);}};definition.observers.tasks.call(c,[{id:'1',sid:'new'}]);assert.equal(c.data.selected,null);c.data.selected={id:'1',sid:'old'};definition.observers.tasks.call(c,[]);assert.equal(c.data.selected,null);const events=[];c.properties={tasks:[{id:'1',sid:'new'}]};c.triggerEvent=(...args)=>events.push(args);definition.methods.select.call(c,{currentTarget:{dataset:{id:'1'}}});assert.deepEqual(events,[['refresh',{id:'1'}]]);});
